import type { UIDataTypes, UIMessage } from "ai";

export interface BartTarget {
  id: string;
  description: string;
  /**
   * Opt-in for the interact tool: the model may click this element. The
   * element itself must also be a natively clickable control (button-like);
   * highlightable never implies clickable.
   */
  interactive?: boolean;
}

export interface BartRoute {
  route: string;
  title: string;
  description: string;
  targets: BartTarget[];
}

/** Generated by `bart sync`. Safe to ship to the browser: no markdown bodies. */
export interface BartPublicManifest {
  routes: BartRoute[];
}

/** A contextual task displayed before a conversation begins. */
export interface BartStarterPrompt {
  label: string;
  prompt: string;
}

/** Consumer-owned appearance and timing for the page highlight overlay. */
export interface BartHighlightOptions {
  durationMs?: number;
  padding?: number;
  borderColor?: string;
  borderWidth?: number;
  borderStyle?: "solid" | "dashed" | "dotted";
  backgroundColor?: string;
  ringColor?: string;
  borderRadius?: string;
}

export type ToolPolicy = "auto" | "confirm" | "disabled";

export interface BartToolPolicies {
  navigate: ToolPolicy;
  highlight: ToolPolicy;
  interact: ToolPolicy;
}

export interface NavigateInput {
  route: string;
}

export interface HighlightInput {
  target: string;
}

export interface InteractInput {
  target: string;
}

export interface BartToolOutput {
  ok: boolean;
  reason?: string;
  /** True when the user clicked Allow on the approval card (vs. auto policy). */
  approvedByUser?: boolean;
}

export interface BartTools {
  navigate: { input: NavigateInput; output: BartToolOutput };
  highlight: { input: HighlightInput; output: BartToolOutput };
  interact: { input: InteractInput; output: BartToolOutput };
  [k: string]: { input: unknown; output: unknown };
}

export type BartUIMessage = UIMessage<unknown, UIDataTypes, BartTools>;

export type BartVariant = "dock" | "sidebar" | "spotlight";

/** Surface finish shared by every shell: opaque (default) or backdrop-blur. */
export type BartAppearance = "default" | "glass";
